networks:
  telemetry-monitoring:
    driver: bridge
    name: telemetry-monitoring

services:
  tempo:
    container_name: tempo
    image: grafana/tempo:main-567e7f7
    networks:
      - telemetry-monitoring
    user: root
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
      - ./tmp-tempo-data:/tmp/tempo
    ports:
      - 3200:3200
      - 4317:4317
      - 4318:4318

  grafana:
    container_name: grafana
    image: grafana/grafana:11.0.0
    networks:
      - telemetry-monitoring
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      # - GF_SMTP_ENABLED=true
      # - GF_SMTP_HOST=smtp.gmail.com:587
      # - GF_SMTP_USER=anbiasenggagau@gmail.com
      # - GF_SMTP_PASSWORD=supersecret
      # - GF_SMTP_SKIP_VERIFY=false
      # - GF_SMTP_FROM_NAME=NO-REPLY
      # - GF_SMTP_FROM_ADDRESS=anbiasenggagau@gmail.com
    ports:
      - 3000:3000

  loki:
    container_name: loki
    image: grafana/loki:main-bdfc86b
    networks:
      - telemetry-monitoring
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml:ro
    ports:
      - 3100:3100
